### ISSUE TITLE
No such file or directory: './data/const_array.mat'

### ISSUE THREAD

**Issue by soumya997** [QianSong-Cherry/SAR-Colorization-v2#1]
Thank you @QianSong-Cherry for the amazing paper `Radar Image Colorization`.
Actually, I was trying to run the `main.py` by following the steps provided in the readme. But after running the file I am getting this error message,
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/scipy/io/matlab/mio.py", line 39, in _open_file
    return open(file_like, mode), True
FileNotFoundError: [Errno 2] No such file or directory: './data/const_array.mat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 8, in <module>
    import utils
  File "/content/SAR-Colorization-v2/utils.py", line 15, in <module>
    data1 = sio.loadmat(matfn)
  File "/usr/local/lib/python3.7/dist-packages/scipy/io/matlab/mio.py", line 216, in loadmat
    with _open_file_context(file_name, appendmat) as f:
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.7/dist-packages/scipy/io/matlab/mio.py", line 19, in _open_file_context
    f, opened = _open_file(file_like, appendmat, mode)
  File "/usr/local/lib/python3.7/dist-packages/scipy/io/matlab/mio.py", line 45, in _open_file
    return open(file_like, mode), True
FileNotFoundError: [Errno 2] No such file or directory: './data/const_array.mat'

```

Here are the things that I did https://colab.research.google.com/drive/1P0ZqoI3Q8v5GCm_YMjvh-oCD3rUsHrMH?usp=sharing
I guess this is happening because that `const_array.mat` file is not present in the data directory. https://github.com/QianSong-Cherry/SAR-Colorization-v2/blob/master/utils.py#L14. There were not any instructions regarding the `const_array.mat` file. 
### So if anybody can help then it would be very helpful for me
@QianSong-Cherry [@fudanxu](https://github.com/fudanxu)

**Comment by QianSong-Cherry** [comment]
See Line 22 and 24 in main.m

**Comment by soumya997** [comment]
The issue is resolved now.
If you are facing the same problem, then do these steps,
1. change the `~` from line 14 to 22 of the `pre_data_tf.m` file.
2.  Also change the `~` from lines 10,34,46 and 67 of the `main.m` file.
3. then run both the files `pre_data_tf.m` and `main.m` respectively.

After this, a file called `const_array.mat` will be created, after that, you will be able to run `main.py` properly. In the readme, it is not mentioned that we also need to run `main.m` file. 
Thanks to @QianSong-Cherry for helping me out with this problem.
